"""
Assemble output/findings.md from the query CSVs: headline numbers, the category-wide vs
app-specific table, the per-app top-3, release deltas and the India-vs-global split.
The narrative paragraphs at the top are written by hand in findings.md after reading the
tables; this script regenerates only the data sections between the markers.

    python src/report.py
"""

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "output"
FINDINGS = OUT / "findings.md"
START, END = "<!-- data:start -->", "<!-- data:end -->"


def md_table(df: pd.DataFrame, cols: list[str], rename: dict | None = None, n: int | None = None) -> str:
    d = df[cols].head(n) if n else df[cols]
    if rename:
        d = d.rename(columns=rename)
    lines = ["| " + " | ".join(d.columns) + " |", "|" + "---|" * len(d.columns)]
    for _, r in d.iterrows():
        lines.append("| " + " | ".join("" if pd.isna(v) else (f"{v:,.1f}" if isinstance(v, float) else str(v)) for v in r) + " |")
    return "\n".join(lines)


def build() -> str:
    mix = pd.read_csv(OUT / "01_complaint_mix_by_app.csv")
    cat = pd.read_csv(OUT / "02_category_wide.csv")
    rel = pd.read_csv(OUT / "03_before_after_release.csv")
    rat = pd.read_csv(OUT / "04_rating_and_upvotes_by_label.csv")
    ig = pd.read_csv(OUT / "06_india_vs_global.csv")
    lang = pd.read_csv(OUT / "07_language_split.csv")
    log = (OUT / "query_log.md").read_text(encoding="utf-8").splitlines()[0]
    classifier = log.split("classifier = ")[-1].rstrip(")")

    apps = mix.drop_duplicates("app")[["app", "segment", "n_reviews", "n_complaints", "complaint_rate_pct", "avg_rating"]]
    total_reviews = int(apps["n_reviews"].sum())
    total_complaints = int(apps["n_complaints"].sum())
    top3 = (mix[mix["rank_in_app"] <= 3].groupby("app")
            .apply(lambda g: ", ".join(f"{r.label} {r.pct_of_complaints:.0f}%" for r in g.itertuples()))
            .rename("top_3_complaints").reset_index())
    apps = apps.merge(top3, on="app").sort_values("complaint_rate_pct", ascending=False)

    s = [START, "", f"_Generated by src/report.py. Classifier: **{classifier}**. "
         f"Reviews: **{total_reviews:,}** across {len(apps)} apps; complaints: **{total_complaints:,}** "
         f"({100 * total_complaints / total_reviews:.0f}%)._", "",
         "### Complaint rate and top 3 complaints per app", "",
         md_table(apps, ["app", "segment", "n_reviews", "complaint_rate_pct", "avg_rating", "top_3_complaints"],
                  {"n_reviews": "reviews", "complaint_rate_pct": "complaint %", "avg_rating": "avg stars"}),
         "", "![complaint mix](charts/complaint_mix_by_app.png)", "",
         "### Category-wide vs app-specific", "",
         "`apps_where_top3` = number of the 15 apps where this is a top-3 complaint. A high average share with low spread is a category problem; a high max with high spread is one app's problem.", "",
         md_table(cat[cat["label"] != "no_complaint"],
                  ["label", "total_complaints", "pct_of_all_complaints", "apps_where_top3", "avg_share_pct", "min_share_pct", "max_share_pct", "stddev_share_pct", "worst_app"],
                  {"total_complaints": "n", "pct_of_all_complaints": "% of all", "avg_share_pct": "avg share", "min_share_pct": "min", "max_share_pct": "max", "stddev_share_pct": "spread"}),
         "", "![category wide](charts/category_wide_vs_specific.png)", "",
         "### Which complaint costs the most stars, and which gets upvoted", "",
         md_table(rat[rat["label"] != "no_complaint"].sort_values("avg_rating"),
                  ["label", "n", "avg_rating", "pct_one_star", "avg_thumbs_up", "pct_of_all_thumbs_up", "pct_mentions_update"],
                  {"avg_rating": "avg stars", "pct_one_star": "% 1-star", "avg_thumbs_up": "avg helpful votes", "pct_of_all_thumbs_up": "% of all votes", "pct_mentions_update": "% blame an update"}),
         "", "![rating by label](charts/rating_by_label.png)", "",
         "### India-built coaching apps vs global trackers", "",
         md_table(ig[ig["label"] != "no_complaint"], ["label", "india_built_pct", "global_pct", "platform_pct", "india_minus_global_pp"],
                  {"india_built_pct": "India-built %", "global_pct": "global %", "platform_pct": "Samsung Health %", "india_minus_global_pp": "diff (pp)"}),
         "", "![india vs global](charts/india_vs_global.png)", "",
         "### Releases that moved the needle (30 days before vs after first sighting of a version)", "",
         "Release date is a proxy (first review on that version). Positive `complaint_delta_pp` = complaints rose after the release.", ""]
    if len(rel):
        s += [md_table(rel.sort_values("complaint_delta_pp", ascending=False),
                       ["app", "app_version", "release_proxy_date", "n_before", "n_after", "rating_before", "rating_after", "complaint_delta_pp", "crash_delta_pp", "mentions_update_pct_after"],
                       {"release_proxy_date": "first seen", "complaint_delta_pp": "complaint Δpp", "crash_delta_pp": "crash Δpp", "mentions_update_pct_after": "% blame update"}, n=12),
              "", "Releases that *reduced* complaints most:", "",
              md_table(rel.sort_values("complaint_delta_pp").head(5),
                       ["app", "app_version", "release_proxy_date", "complaint_pct_before", "complaint_pct_after", "complaint_delta_pp"])]
    else:
        s += ["_No version with 50+ reviews on both sides of its first sighting._"]
    s += ["", "![monthly trend](charts/monthly_complaint_trend.png)", "",
          "### Language split", "",
          md_table(lang.groupby("lang_hint").head(5), ["lang_hint", "n_reviews", "avg_rating", "complaint_pct", "label", "share_of_complaints_pct"]),
          "", END]
    return "\n".join(s)


def main() -> None:
    data = build()
    if FINDINGS.exists():
        txt = FINDINGS.read_text(encoding="utf-8")
        if START in txt and END in txt:
            pre, rest = txt.split(START, 1)
            _, post = rest.split(END, 1)
            FINDINGS.write_text(pre + data + post, encoding="utf-8")
            print(f"updated data section in {FINDINGS}")
            return
    FINDINGS.write_text("# Findings\n\n_(narrative to be written)_\n\n" + data + "\n", encoding="utf-8")
    print(f"wrote {FINDINGS}")


if __name__ == "__main__":
    main()
